### PR TITLE
Added hero_messages files to chatwheel, and updated some others

### PR DESCRIPTION
**Pull request by mdiller**
Ran a simple python script that used dotabase and my extracted vpk files to add these files to the repository. This should include all of the files referenced in the current `chat_wheel.json`

### CODE REVIEW

**Comment by mdiller** [comment]
All of the mappings for that is in the vpk at `/scripts/chat_wheel.txt`. I'm guessing we'll want to have something in dotaconstants that has our version of that file?

**Comment by howardchung** [comment]
We don't because I think we get the IDs from the replay, but we should have a link to that text file in this repo (or a copy of it) to use as a reference.

**Comment by mdiller** [comment]
Don't we want the text to show for the chat log?
image

Currently all of that text is missing. IIRC we were storing it in the lang files in the web repo but im guessing we dont want to put 1000 new entries in there.

It also would be cool to add the icon of the dota+ level needed to say the clip, because thats what it shows in game. All that information is available in the `chat_wheel` file:
```json
{
	"message_id": "106004",
	"label": "#dota_chatwheel_label_ember_spirit_1",
	"message": "#dota_chatwheel_message_ember_spirit_1",
	"sound": "ember_spirit_embr_attack_06",
	"all_chat": "1",
	"unlock_hero_badge_tier": "SilverTier"
}
```

Also, some of the audio files have different file types, so we cant link to it if all we know is the ID. Most of the hero response audio is mp3, some is aac and wav.

**Comment by howardchung** [comment]
oh yeah, we'll need to figure out how to get the strings into the language file (or load the mappings from somewhere else)

**Comment by howardchung** [comment]
probably dotaconstants makes the most sense then

**Comment by mdiller** [comment]
One issue with setting that up is currently we're getting all the files for building dotaconstants from d2vpkr, and they don't have a json version of the chat_wheel.txt file. If i remember right, its KV3 format and last time i looked there weren't any javascript libraries for reading/converting that to json.

For dotabase I'm converting it using some regex that I cobbled together that isn't guaranteed to work on all kv3 files so idk if we wanna use that.

**Comment by howardchung** [comment]
isn't it just vdf?

https://www.npmjs.com/package/simple-vdf is what we use in core

**Comment by mdiller** [comment]
Whoops, I thought I remembered checking that a while back and it didn't work for KV3 files but it looks like it is working now! I'll get on adding that at some point in the next few days.

**Pull request merged**
